### ISSUE TITLE
install-apk.sh 查找apk的问题

### ISSUE THREAD

**Issue by MarkMjw** [hi-dhl/SyncKit#1]
`
find . | fgrep ".apk" 
`

这里似乎有些问题，我这里找到的文件路径如下：

>  ./app/build/intermediates/apk/debug/app-debug.apk.idsig
>  adb: filename doesn't end .apk or .apex: ./app/build/intermediates/apk/debug/app-debug.apk.idsig

导致无法安装，是否可以修改为：

`
find . -name "*.apk" 
`

版本信息：Android Studio Dolphin | 2021.3.1   
AGP：7.3.0  
Gradle: 7.4.2

**Comment by hi-dhl** [comment]
收到，这里我修复一下， 但是奇怪得是怎么会生成 apk.idsig 文件

**Comment by hi-dhl** [comment]
感谢你的提交和建议，已经修复，将会跟着新版一起发出去
