### ISSUE TITLE
我按照 步骤执行点击远程编译就报错这个  可是文件夹路径是有的

### ISSUE THREAD

**Issue by zzh-xhz** [hi-dhl/SyncKit#14]
exec action fail com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "\bin\bash" (in directory "D:\code\peopledaily-video"): CreateProcess error=2, 系统找不到指定的文件。

**Comment by hi-dhl** [comment]
你用的应该是 win，现在不支持 win

**Comment by hi-dhl** [comment]
以后会支持
