### ISSUE TITLE
请输入远程设备的端口号

### ISSUE THREAD

**Issue by CatHash35** [hi-dhl/SyncKit#2]
版本：1.6
![image](https://user-images.githubusercontent.com/49141982/194787562-00236ea9-f098-4b44-a902-25435e61df9c.png)

**Comment by hi-dhl** [comment]
<img width="304" alt="image" src="https://user-images.githubusercontent.com/16751752/194794374-f926263f-9c75-4dd2-9a05-f68b28a6a877.png">

点击一下插件配置，设置一下 ip 和端口号，就可以了

**Comment by CatHash35** [comment]
> <img alt="图片" width="304" src="https://user-images.githubusercontent.com/16751752/194794374-f926263f-9c75-4dd2-9a05-f68b28a6a877.png">
> 
> 点击一下插件配置，设置一下 ip 和端口号，就可以了

你好。我点击插件配置依旧弹出。（其他按钮也试过、也配置了服务器的key和本地的key也是无效）。会是因为不是最新版本吗？我看到您在昨天有更新过（解决YES端口号）？但是github 的release版本是3天前的。

**Comment by hi-dhl** [comment]
yes 、 no  是首次访问的时候才会出现，这个会跟下次的版本一起上， 但是你的问题是 「弹窗提示未设置端口号」 这是因为，当前项目下面有个 .sync/service/config.json 不存在导致的，如下图所示

<img width="478" alt="image" src="https://user-images.githubusercontent.com/16751752/194809333-093f9037-838a-44bb-a771-59bae353070c.png">

确认一下上面的文件是否存在，如果存在，辛苦贴一下里面的内容， 如果不存在点击一下初始化，看看会不会不会生成

**Comment by CatHash35** [comment]
> yes 、 no 是首次访问的时候才会出现，这个会跟下次的版本一起上， 但是你的问题是 「弹窗提示未设置端口号」 这是因为，当前项目下面有个 .sync/service/config.json 不存在导致的，如下图所示
> 
> <img alt="image" width="478" src="https://user-images.githubusercontent.com/16751752/194809333-093f9037-838a-44bb-a771-59bae353070c.png">
> 
> 确认一下上面的文件是否存在，如果存在，辛苦贴一下里面的内容， 如果不存在点击一下初始化，看看会不会不会生成

.sync 没有文件。点击初始化，提示成功，依旧没有生成文件

**Comment by hi-dhl** [comment]
<img width="436" alt="image" src="https://user-images.githubusercontent.com/16751752/194810746-b4378f68-86ad-4692-91ac-98c8c19bb26d.png">

AndroidStudio  右下角有个 Event Log, 点击初始化之后，里面会有一些错误日志

**Comment by CatHash35** [comment]
> <img alt="image" width="436" src="https://user-images.githubusercontent.com/16751752/194810746-b4378f68-86ad-4692-91ac-98c8c19bb26d.png">
> 
> AndroidStudio 右下角有个 Event Log, 点击初始化之后，里面会有一些错误日志

![image](https://user-images.githubusercontent.com/49141982/194811575-b1ba44fb-adf7-47f2-8ae7-109c9fc3f6f7.png)

**Comment by hi-dhl** [comment]
收到，我现在修复一下

**Comment by CatHash35** [comment]
> 收到，我现在修复一下

感谢

**Comment by hi-dhl** [comment]
https://github.com/hi-dhl/SyncKit/releases

1.7 的版本已经发布，辛苦帮忙安装新版本，看一下是否解决这个问题，如果没有解决，会在 Event Log 输出一些错误日志

**Comment by CatHash35** [comment]
> https://github.com/hi-dhl/SyncKit/releases
> 
> 1.7 的版本已经发布，辛苦帮忙安装新版本，看一下是否解决这个问题，如果没有解决，会在 Event Log 输出一些错误日志

您好。已经更新到1.7的版本。初始化后依旧没有生成文件。日志如下![image](https://user-images.githubusercontent.com/49141982/194883038-fa5fa558-5837-46c9-84be-a87cfbd99738.png)

**Comment by hi-dhl** [comment]
很奇怪，读取不到 jar 里面的资源，你好，能否留个联系方式，我发你一个优化后的版本

**Comment by CatHash35** [comment]
> 很奇怪，读取不到 jar 里面的资源，你好，能否留个联系方式，我发你一个优化后的版本

好的。liuyibo35@hotmail.com

**Comment by hi-dhl** [comment]
> > 很奇怪，读取不到 jar 里面的资源，你好，能否留个联系方式，我发你一个优化后的版本
> 
> 好的。[liuyibo35@hotmail.com](mailto:liuyibo35@hotmail.com)

邮件已经发送，辛苦查收
