### ISSUE TITLE
无法执行打包命令的问题

### ISSUE THREAD

**Issue by zhupeipei** [hi-dhl/SyncKit#3]
![image](https://user-images.githubusercontent.com/34636861/195978775-165a1203-da0c-400c-99ab-38f288e001db.png)

这里少个;导致无法实现执行命令诶。
另外，命令能否更多的自定义，我看./gradlew这个前缀写死了

**Comment by hi-dhl** [comment]
这个问题我看一下，  更多自定义命令，后面会支持的

**Comment by hi-dhl** [comment]
https://github.com/hi-dhl/SyncKit/releases/tag/v1.9
新版本修复了这个问题， 更多自定义命令，后面会支持的

**Comment by hi-dhl** [comment]
https://github.com/hi-dhl/SyncKit/releases/tag/v2.0
2.0 已经支持自定义命令了，具体使用可以参考仓库主页 「自定义命令」部分
