### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by fismas** [hi-dhl/SyncKit#5]
前提环境交代：
公司内部共用的编译服务器android-nexus-maven，平时使用ssh -p 命令登录连接服务器，手动同步代码手动gradle assembleDebug 编译并打Debug包。

log日志信息：
 SyncKit v2.0 

 sync start ...... 

Permission denied, please try again.
Permission denied, please try again.
dev@192.168.120.67: Permission denied (publickey,password).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at /AppleInternal/Library/BuildRoots/20d6c351-ee94-11ec-bcaf-7247572f23b4/Library/Caches/com.apple.xbs/Sources/rsync/rsync/io.c(453) [sender=2.6.9]
BUILD FAILED in

**Comment by fismas** [comment]
补充：点击远程编译后没有提示让输入密码，直接就编译失败了

**Comment by hi-dhl** [comment]
@fismas 没有配置ssh 无密码访问，使用ssh -p 命令登录需要输入密码吧？

**Comment by hi-dhl** [comment]
文档中有配置方法  https://github.com/hi-dhl/SyncKit/blob/main/doc/use_synckit.md， 后面我会提供一键化脚本，设置无密码访问

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/16751752/197699635-1d68c8c0-b1f1-4b86-a0e3-f02412ab7f22.png">

**Comment by fismas** [comment]
@hi-dhl 我们这个服务器是公司内部多人使用同一帐号密码来编译的，只是每个人分了不同的目录，所以可能没法设置public key

**Comment by fismas** [comment]
@hi-dhl 看下编译信息里面有用户目录信息，如：source  ~/.bashrc > /dev/null 2>&1; source ~/.bash_profile > /dev/null 2>&1; source ~/.zshrc > /dev/null，像我们这种多人使用同一个帐号和密码的会有影响吗

**Comment by hi-dhl** [comment]
> @hi-dhl 看下编译信息里面有用户目录信息，如：source ~/.bashrc > /dev/null 2>&1; source ~/.bash_profile > /dev/null 2>&1; source ~/.zshrc > /dev/null，像我们这种多人使用同一个帐号和密码的会有影响吗

如果账号是一样的的话，这段代码针对，使用相同账号都生效

**Comment by hi-dhl** [comment]
> @hi-dhl 我们这个服务器是公司内部多人使用同一帐号密码来编译的，只是每个人分了不同的目录，所以可能没法设置public key

也不受影响，如果你配置无密码访问，只有你不需要密码登录，其他人还是需要密码登录的

**Comment by fismas** [comment]
> 

我设置public key，编译还是报同样的错误

**Comment by hi-dhl** [comment]
ssh 连接服务器，需要使用密码吗

**Comment by fismas** [comment]
需要

**Comment by hi-dhl** [comment]
你应该没有root权限改不了，我提供一个带密码访问的方式吧

**Comment by hi-dhl** [comment]
你的 publick key 添加对了吗，方便截图我看一下吗

**Comment by fismas** [comment]
![image](https://user-images.githubusercontent.com/96452729/197715526-003f9e1f-b05e-423f-9bc4-8274a676e7e1.png)

**Comment by hi-dhl** [comment]
尝试执行下面的命令，更改一下 authorized_keys 文件的权限

chmod 777 ~/.ssh
chmod 666 ~/.ssh/authorized_keys

**Comment by fismas** [comment]
还是不行

**Comment by fismas** [comment]
> 

请问什么时候有时间可以发版带密码访问的方式？

**Comment by hi-dhl** [comment]
idea 插件的方式，无法携带密码，只能使用命令行的方式，目前这个还在开发中，会尽快发布

**Comment by hi-dhl** [comment]
https://github.com/hi-dhl/SyncKit/releases/tag/v2.1

从 v2.1 开始，idea 插件支持密码访问远程设备，在弹出的 「插件配置对话框中」输入远程设备的登陆密码即可

<img width="474" alt="image" src="https://user-images.githubusercontent.com/16751752/198823011-f968576c-85f1-4f2c-a5d4-8d5b8f420ca3.png">

**Comment by hi-dhl** [comment]
> https://github.com/hi-dhl/SyncKit/releases/tag/v2.1
> 
> 从 v2.1 开始，idea 插件支持密码访问远程设备，在弹出的 「插件配置对话框中」输入远程设备的登陆密码即可
> 
> <img alt="image" width="474" src="https://user-images.githubusercontent.com/16751752/198823011-f968576c-85f1-4f2c-a5d4-8d5b8f420ca3.png">

@fismas  新版本已经已经支持密码访问

**Comment by hi-dhl** [comment]
@fismas 新版本已经支持密码访问，issue 将会关闭，如果在使用过程中遇到其他问题，欢迎再次提交 issue

**Comment by fismas** [comment]
非常感谢
