### ISSUE TITLE
git 仓库信息没有同步吗

### ISSUE THREAD

**Issue by haizhiyun** [hi-dhl/SyncKit#6]
感谢提供！
------------
git 仓库信息没有同步吗？编译过程中有git 信息的获取，git 仓库信息能否设置可以同步到远程呢

**Comment by hi-dhl** [comment]
在当前项目下 有 .sync 文件夹，按照图示，将 .git 删掉就可以同步了，
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/16751752/200157353-717f5310-a0ad-4833-b3a5-ca3f68c9e556.png">

**Comment by hi-dhl** [comment]
> 在当前项目下 有 .sync 文件夹，按照图示，将 .git 删掉就可以同步了， <img alt="image" width="1000" src="https://user-images.githubusercontent.com/16751752/200157353-717f5310-a0ad-4833-b3a5-ca3f68c9e556.png">

如果图片无法查看，可以按照下面的路径, 打开 local_ignore 文件，删除 .git/ 就可以同步了

> 当前项目根目录 -> .sync 文件夹 -> local_ignore

感谢你的反馈，将会关掉这个issue， 如果还没解决，欢迎再次打开
