### ISSUE TITLE
使用密码登录无法远程编译和同步

### ISSUE THREAD

**Issue by fismas** [hi-dhl/SyncKit#8]
感谢提供这么优秀的工具。

问题描述：
        居家挂的VPN连接公司内网服务器，配置里面填写了密码，编译、同步及远程命令都提示FAILED，如下图：
![image](https://user-images.githubusercontent.com/96452729/203467409-9242f26d-d262-4541-8837-000b90617af3.png)

**Comment by hi-dhl** [comment]
<img width="311" alt="image" src="https://user-images.githubusercontent.com/16751752/203520765-567dc8c1-304c-4f1b-9fdc-f2983dee07dd.png">

右下角有个 event log， 帮忙看一下，有没有相关的错误日志输出

**Comment by fismas** [comment]
没有任何有用的错误log输出。
编译时报：18:20	BUILD FAILED in , error code 1
同步时啥也没有log输出
![image](https://user-images.githubusercontent.com/96452729/203523153-8828f128-8008-47a8-91a1-c4654441035b.png)

**Comment by hi-dhl** [comment]
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/16751752/203698692-a06e47a9-ed8c-41f4-8888-6df103dfed97.png">
 
图示位置，点击一下，会有一串命令，发给我看一下吧

**PS: 命令中包含  IP  、密码 和用户名，需要打上马赛克，在发出来**

**Comment by hi-dhl** [comment]
> <img alt="image" width="1205" src="https://user-images.githubusercontent.com/16751752/203698692-a06e47a9-ed8c-41f4-8888-6df103dfed97.png">
> 
> 图示位置，点击一下，会有一串命令，发给我看一下吧
> 
> PS: 命令中包含 IP 、密码 和用户名，需要打上马赛克，在发出来

@fismas

**Comment by fismas** [comment]
/bin/bash -c "set +e;chmod 777 /Users/.../develop/.sync/script/install-sshpass.sh && bash /Users/.../develop/.sync/script/install-sshpass.sh && sshpass  -p  '****'    rsync -e 'ssh -p 2222  -o StrictHostKeyChecking=no' --archive --delete --progress --rsync-path='export LC_ALL=en_US.UTF-8;export LANG=en_US.UTF-8;mkdir -p ~/code/.../develop/;rm -rf ~/code/.../develop//local.properties;echo sdk.dir=/opt/sdk >> ~/code/.../develop//local.properties && rsync' --exclude-from=/Users/.../develop/.sync/local_ignore  /Users/.../develop/  dev@192.168.1.67:~/code/.../develop/  && set +e;chmod 777 /Users/.../develop/.sync/script/install-sshpass.sh && bash /Users/.../develop/.sync/script/install-sshpass.sh && sshpass  -p  '****'   ssh -p 2222  -o StrictHostKeyChecking=no dev@192.168.1.67  ' set +e;source  ~/.bashrc > /dev/null 2>&1; source ~/.bash_profile > /dev/null 2>&1; source ~/.zshrc > /dev/null 2>&1;cd ~/code/.../develop/  && ./gradlew assembleDebug'  && set +e;chmod 777 /Users/.../develop/.sync/script/install-sshpass.sh && bash /Users/.../develop/.sync/script/install-sshpass.sh && sshpass  -p  '****'   rsync -e 'ssh -p 2222 -o StrictHostKeyChecking=no' --archive --progress --include-from=/Users/.../develop/.sync/remote_include  --exclude-from=/Users/.../develop/.sync/remote_ignore   dev@192.168.1.67:~/code/.../develop/ /Users/.../develop  && chmod 777 /Users/.../develop/.sync/script/install-apk.sh && bash /Users/.../develop/.sync/script/install-apk.sh com.***.splash.SplashNewActivity "

**Comment by fismas** [comment]
/bin/bash -c "set +e;chmod 777 /Users/.../develop/.sync/script/install-sshpass.sh && bash /Users/.../develop/.sync/script/install-sshpass.sh && sshpass  -p  'xxxx'    rsync -e 'ssh -p 2222  -o StrictHostKeyChecking=no' --archive --delete --progress --rsync-path='export LC_ALL=en_US.UTF-8;export LANG=en_US.UTF-8;mkdir -p ~/code/.../develop/;rm -rf ~/code/.../develop//local.properties;echo sdk.dir=/opt/sdk >> ~/code/.../develop//local.properties && rsync' --exclude-from=/Users/.../develop/.sync/local_ignore  /Users/.../develop/  dev@192.168.1.67:~/code/.../develop/  && set +e;chmod 777 /Users/.../develop/.sync/script/install-sshpass.sh && bash /Users/.../develop/.sync/script/install-sshpass.sh && sshpass  -p  'xxxx'   ssh -p 2222  -o StrictHostKeyChecking=no dev@192.168.1.67  ' set +e;source  ~/.bashrc > /dev/null 2>&1; source ~/.bash_profile > /dev/null 2>&1; source ~/.zshrc > /dev/null 2>&1;cd ~/code/.../develop/  && ./gradlew assembleDebug'  && set +e;chmod 777 /Users/.../develop/.sync/script/install-sshpass.sh && bash /Users/.../develop/.sync/script/install-sshpass.sh && sshpass  -p  'xxxx'   rsync -e 'ssh -p 2222 -o StrictHostKeyChecking=no' --archive --progress --include-from=/Users/.../develop/.sync/remote_include  --exclude-from=/Users/.../develop/.sync/remote_ignore   dev@192.168.1.67:~/code/.../develop/ /Users/.../develop  && chmod 777 /Users/.../develop/.sync/script/install-apk.sh && bash /Users/.../develop/.sync/script/install-apk.sh com.xxxx.splash.SplashNewActivity "

**Comment by hi-dhl** [comment]
@fismas 
sshpass -p '密码' ssh  -o StrictHostKeyChecking=no  远程设备用户名@远程设备IP -p端口号

ps: 密码要带上单引号

执行上面命令是否可以在不输入密码的情况，连接远程设备

**Comment by fismas** [comment]
提示：-bash: sshpass: command not found

**Comment by hi-dhl** [comment]
@fismas 
<img width="822" alt="image" src="https://user-images.githubusercontent.com/16751752/203707552-e24e32c1-6cd2-4713-9c9a-993c26f27907.png">

自动化执行安装 sshpass 脚本失败了，  手动执行图示的脚本

**Comment by fismas** [comment]
执行脚本没有任何log输出，执行sshpass -h还是提示-bash: sshpass: command not found

**Comment by hi-dhl** [comment]
我大概知道了，你应该是低版本直接升级到高版本的，所以本地没有  sshpass 工具包。

点击一下初始化， 会生成   sshpass 工具包。

PS: 重新初始化会覆盖你之前填入的信息，需要重新填一下

<img width="236" alt="image" src="https://user-images.githubusercontent.com/16751752/203788187-dd9492c2-3740-465c-be54-2ca954a9906d.png">

**Comment by hi-dhl** [comment]
> 我大概知道了，你应该是低版本直接升级到高版本的，所以本地没有 sshpass 工具包。
> 
> 点击一下初始化， 会生成 sshpass 工具包。
> 
> PS: 重新初始化会覆盖你之前填入的信息，需要重新填一下
> 
> <img alt="image" width="236" src="https://user-images.githubusercontent.com/16751752/203788187-dd9492c2-3740-465c-be54-2ca954a9906d.png">


初始化完成，点击一下同步，是否可以正常工作

**Comment by fismas** [comment]
不行还是一样，我在file目录下看到有sshpass包，不知道是不是你说的。
![image](https://user-images.githubusercontent.com/96452729/203879559-455f8a4a-ea90-42fa-9b4d-99ae1ee8fa81.png)

**Comment by hi-dhl** [comment]
还是没有任何日志输出吗，方便加我wechat的吗 hi-dhl

**Comment by hi-dhl** [comment]
感谢反馈，新版本 2.4 解决了这个问题
https://github.com/hi-dhl/SyncKit/releases/tag/2.4
